// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLiT0WcPC2GRei3-OO5dg6nD2iwOfzXpA',
    appId: '1:471484607522:web:600f705d8ee6d0414e2e7b',
    messagingSenderId: '471484607522',
    projectId: 'flutter-to-do-app-b727e',
    authDomain: 'flutter-to-do-app-b727e.firebaseapp.com',
    storageBucket: 'flutter-to-do-app-b727e.appspot.com',
    measurementId: 'G-58RKZFN0NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhtN1Znklmepdes6AeIMVh_a-G214rvIM',
    appId: '1:471484607522:android:ea3821446675687f4e2e7b',
    messagingSenderId: '471484607522',
    projectId: 'flutter-to-do-app-b727e',
    storageBucket: 'flutter-to-do-app-b727e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxsizWcjs-U2KuI1L9v6VEHxz6m3avN1I',
    appId: '1:471484607522:ios:00e352bcae40ef414e2e7b',
    messagingSenderId: '471484607522',
    projectId: 'flutter-to-do-app-b727e',
    storageBucket: 'flutter-to-do-app-b727e.appspot.com',
    iosBundleId: 'com.example.flutterToDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxsizWcjs-U2KuI1L9v6VEHxz6m3avN1I',
    appId: '1:471484607522:ios:32ddb25cf31e58bd4e2e7b',
    messagingSenderId: '471484607522',
    projectId: 'flutter-to-do-app-b727e',
    storageBucket: 'flutter-to-do-app-b727e.appspot.com',
    iosBundleId: 'com.example.flutterToDoApp.RunnerTests',
  );
}
